---
title: "ST704 Team Project"
author: "Sohyeon and Jisu"
output: html_document
---

```{r warning = FALSE, message = FALSE}
library(tidyverse)
library(stringi)
library(rebus)
library(glmnet)
library(pander)
library(rqPen)
library(quantreg)
library(xgboost)
library(rpart.plot)
library(DiagrammeR)
library(lars)
library(car)
```


```{r}
setwd("/Users/sohyeonkim/Github/ST704_Project")
Data <- read.csv("Salary_Data.csv") %>% as_tibble()
Data[which(Data$index == 741), "Headquarters"] <- "Boston, MA" # Manually fill the missing value
```

# EDA

```{r}
# Data Manipulation
Data_pretty <- Data %>% dplyr::select(-c(Salary.Estimate, Job.Description, Job.Title, company_txt, Age, Job.Location)) %>% # Remove duplicated values
  separate(col = Headquarters, into = c("Headquarters.City", "Headquarters.State"), sep = ",") %>%
  mutate(Rating = ifelse(Rating == -1, NA, Rating), # Indicate NA
         Founded = ifelse(Founded == -1, NA, Founded), 
         # Remove "\nRatings" in Company.Name
         Company.Name = str_remove_all(Company.Name, pattern = "\n" %R% DGT %R% "." %R% DGT %R% END), 
         # Cannot apply separate function to Location because Santa Fe Springs, so manually separate it.
         City = str_remove(Location, pattern = "," %R% SPC %R% one_or_more(WRD) %R% END),
         State = str_extract(Location, pattern = SPC %R% one_or_more(WRD) %R% END) 
                 %>% str_remove(pattern = SPC), 
         Headquarters.State = str_remove(Headquarters.State, pattern = SPC),
         Headquarters.Country = case_when(nchar(Headquarters.State) == 2 ~ "U.S.A.", 
                                          TRUE ~ Headquarters.State),
         job_title_sim = case_when(job_title_sim == "Data scientist project manager"
                                   ~ "DS project manager", 
                                   job_title_sim == "machine learning engineer" ~ "ML engineer", 
                                   job_title_sim == "na" ~ "others", 
                                   TRUE ~ job_title_sim),
         Type.of.ownership = case_when(Type.of.ownership == "Company - Private" ~ "Private", 
                                       Type.of.ownership == "Other Organization" ~ "Other",
                                       Type.of.ownership == "Company - Public" ~ "Public", 
                                       Type.of.ownership == "Subsidiary or Business Segment" 
                                       ~ "Subsidiary", 
                                       Type.of.ownership == "Nonprofit Organization" ~ "NPO",
                                       Type.of.ownership == "College / University" ~ "Univ",
                                       Type.of.ownership == "School / School District" ~ "School", 
                                       TRUE ~ Type.of.ownership),
         Competitors = ifelse(Competitors == -1, "None", "Exist"),
         Sector = ifelse(Sector == "-1", "Others", Sector),
         Revenue = str_remove(Revenue, pattern = " \\(USD\\)") %>%
           str_replace(pattern = "million", replacement = "M.") %>%
           str_replace(pattern = "billion", replacement = "B."), 
         Revenue = ifelse(Revenue == "Unknown / Non-Applicable", "unknown", Revenue)) %>%
  select(-c(Location, Company.Name, Headquarters.City, Headquarters.State)) %>%
  rename(Job.Title = job_title_sim) 

factor_col_idx <- c("Hourly", "Employer.provided", "Python", "spark", "aws", 
                    "excel", "sql", 
                    "sas", "keras", "pytorch", "scikit", "tensor", "hadoop", "tableau", 
                    "bi", "flink", "mongo", "google_an")
Data_pretty[factor_col_idx] <- lapply(Data_pretty[factor_col_idx], as.factor)

Data_pretty <- na.omit(Data_pretty)
Data_pretty$Size <- factor(Data_pretty$Size, levels = c("unknown", "1 - 50 ", "51 - 200 ", "201 - 500 ", 
                                                           "501 - 1000 ", "1001 - 5000 ", 
                                                           "5001 - 10000 ", "10000+ "))
Data_pretty$Revenue <- factor(Data_pretty$Revenue, 
                              levels = c("unknown", "$1 to $5 M.", "$5 to $10 M.", "$10 to $25 M.", "$25 to $50 M.", "$50 to $100 M.", "$100 to $500 M.", "$500 M. to $1 B.", "$1 to $2 B.", 
                                         "$2 to $5 B.", "$5 to $10 B.", "$10+ B." ))

```




```{r}
summary(Data_pretty)
```


```{r eval = FALSE}
get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
quant_var <- colnames(Data_pretty)[sapply(Data_pretty, FUN = is.numeric)][-1]

Cor_mat <- Data_pretty %>% dplyr::select(quant_var) %>% cor %>% get_upper_tri()
melted_cormat <- reshape2::melt(Cor_mat, na.rm = TRUE)
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
```

```{r eval = FALSE}
charac_col <- colnames(Data_pretty)[sapply(Data_pretty, FUN = is.character)][-c(2, 3, 4, 8, 9)]

qual_var <- charac_col
plot_list <- vector(mode = "list", length = length(qual_var))

for(idx in 1:length(qual_var)) {
  sub_data <- Data_pretty %>% dplyr::select(qual_var[idx], Avg.Salary.K.) %>% `colnames<-`(value = c("Var", "Salary")) 
  sub_plot <- sub_data %>% ggplot(mapping = aes(x = Var, y = Salary, fill = Var)) +
    geom_boxplot() +
    labs(x = qual_var[idx]) +
    guides(fill=guide_legend(title=qual_var[idx])) +
    theme(axis.text.x = element_text(angle = 45,hjust=1), 
          legend.position = "none")
    #theme(axis.title.x=element_blank(),
    #    axis.text.x=element_blank(),
    #    axis.ticks.x=element_blank())
  plot_list[[idx]] <- sub_plot
}

gridExtra::grid.arrange(
  grobs = plot_list[c(3,4)],
  widths = c(1,1),
  layout_matrix = rbind(c(1,2))
)

```

```{r eval = FALSE}
charac_col <- colnames(Data_pretty)[sapply(Data_pretty, FUN = is.character)][c(2, 3, 4, 8, 9)]

sub_data <- Data_pretty %>% dplyr::select(Sector, Avg.Salary.K.) %>% `colnames<-`(value = c("Var", "Salary")) 
  sub_plot <- sub_data %>% ggplot(mapping = aes(x = Var, y = Salary, fill = Var)) +
    geom_boxplot() +
    labs(x = "Sector") +
    guides(fill=guide_legend(title=qual_var[idx])) +
    theme(axis.text.x = element_text(angle = 45,hjust=1), 
          legend.position = "none")
```



```{r eval = FALSE}
factor_col <- colnames(Data_pretty)[sapply(Data_pretty, FUN = is.factor)][c(1, 2)]

qual_var <- factor_col
plot_list <- vector(mode = "list", length = length(qual_var))

for(idx in 1:length(qual_var)) {
  sub_data <- Data_pretty %>% dplyr::select(qual_var[idx], Avg.Salary.K.) %>% `colnames<-`(value = c("Var", "Salary")) 
  sub_plot <- sub_data %>% ggplot(mapping = aes(x = Var, y = Salary, fill = Var)) +
    geom_boxplot() +
    labs(x = qual_var[idx]) +
    guides(fill=guide_legend(title=qual_var[idx])) +
    theme(axis.text.x = element_text(angle = 45,hjust=1), 
          legend.position = "none")
    #theme(axis.title.x=element_blank(),
    #    axis.text.x=element_blank(),
    #    axis.ticks.x=element_blank())
  plot_list[[idx]] <- sub_plot
}

```

```{r eval = FALSE}
computing_idx <- colnames(Data_pretty)[sapply(Data_pretty, FUN = is.factor)][5:20]

Data_pretty %>% dplyr::select(computing_idx, Avg.Salary.K.) %>%
  pivot_longer(cols = -Avg.Salary.K., names_to = "Language") %>%
  ggplot(mapping = aes(x = value, y = Avg.Salary.K., fill = value)) +
  geom_boxplot() + 
  facet_wrap(~Language)
```

```{r}
Sector_percent <- (Data_pretty$Sector %>% table)/(nrow(Data_pretty))
Other_sector <- Sector_percent[Sector_percent < 0.05] %>% names()

Data_pretty <- Data_pretty %>%
  dplyr::select(-c(index, Industry, Hourly, Employer.provided, Lower.Salary, Upper.Salary, City, State)) %>%
  mutate(Headquarters.Country = ifelse(Headquarters.Country != "U.S.A.", "non-U.S.A.", Headquarters.Country), 
         Sector = ifelse(Sector %in% Other_sector, "Other", Sector), 
         Type.of.ownership = ifelse(Type.of.ownership %in% c("Other", "Univ", "School"), "Other", Type.of.ownership))
```


```{r}
set.seed(10)
train <- sample(1:nrow(Data_pretty), round(3*nrow(Data_pretty)/4))
train_data <- Data_pretty[train, ]
test_data <- Data_pretty[-train, ]

train_y <- train_data$Avg.Salary.K.
test_y <- test_data$Avg.Salary.K.
train_X <- model.matrix(Avg.Salary.K. ~., data = train_data)[, -1]
test_X <- model.matrix(Avg.Salary.K. ~., data = test_data)[, -1]
colnames(train_X)[!(colnames(train_X) %in% colnames(test_X))]
colnames(test_X)[!(colnames(test_X) %in% colnames(train_X))]

ncol(train_X)
ncol(test_X)
```

```{r}
colnames(train_data)
lm(Avg.Salary.K. ~ ., data = train_data) %>% vif
```



# Ridge

```{r}
set.seed(1)

par(mfrow = c(1, 2))
ridge <- glmnet(train_X, train_y, alpha = 0, standardized = TRUE, nlambda = 100)
plot(ridge, label = TRUE, xvar = "lambda")

ridge_cv <- cv.glmnet(train_X, train_y, alpha = 0, nlambda = 100)
plot(ridge_cv)
```


```{r}
ridge_cv$lambda.min
ridge_cv$lambda.1se
```

```{r}
SSE_ridge <- (predict(ridge, test_X, s = ridge_cv$lambda.1se) - test_y)^2
(MSE_ridge <- mean(SSE_ridge))
(se_MSE_ridge <- sd(SSE_ridge)/sqrt(length(test_y)))
coef_ridge <- coef(ridge, s = ridge_cv$lambda.1se)
```



# Lasso

```{r}
par(mfrow = c(1, 2))

set.seed(1)
lasso <- glmnet(train_X, train_y, alpha = 1, standardize = TRUE, nlambda = 100)
plot(lasso, label = TRUE, xvar = "lambda")

set.seed(10)
lasso_cv <- cv.glmnet(train_X, train_y, alpha = 1)
plot(lasso_cv)
```



```{r}
lasso_cv$lambda.min
lasso_cv$lambda.1se
```

```{r}
SSE_lasso <- (predict(lasso, test_X, s = lasso_cv$lambda.1se) - test_y)^2
(MSE_lasso <- mean(SSE_lasso))
(SE_MSE_lasso <- sd(SSE_lasso)/sqrt(length(test_y)))
coef_lasso <- coef(lasso, s=lasso_cv$lambda.1se)
```


# LARS

```{r}
library(lars)
set.seed(1)
fit.lars = lars(train_X, train_y, type="lar")
cv.fit.lars = cv.lars(train_X, train_y, type="lar"); cv.fit.lars
which.min(cv.fit.lars$cv)
plot(fit.lars, "norm")
 
SSE_lars = (predict(fit.lars, test_X, s=58, mode="step")$fit - test_y)^2
MSE_lars = mean(SSE_lars)
SE_lars = sd(SSE_lars)/sqrt(length(test_y))
MSE_lars; SE_lars

coefficients.lar = coef(fit.lars)

set.seed(1)
fit.lars.lasso = lars(train_X, train_y, type="lasso")
plot(fit.lars.lasso, "norm")

coef(fit.lars.lasso)
```

```{r}
cor(train_y - train_X %*% coefficient.lars[6,],train_X[,11] )
cor(train_y - train_X %*% coefficient.lars[6,],train_X[,32] )
cor(train_y - train_X %*% coefficient.lars[6,],train_X[,34] )
cor(train_y - train_X %*% coefficient.lars[6,],train_X[,53] )
cor(train_y - train_X %*% coefficient.lars[6,],train_X[,60] )
```


# Kernel Regression

```{r}
train_data2 = train_data
train_data2$Type.of.ownership = as.factor(train_data2$Type.of.ownership)
train_data2$Sector = as.factor(train_data2$Sector)
train_data2$Competitors = as.factor(train_data2$Competitors)
train_data2$Job.Title = as.factor(train_data2$Job.Title)
train_data2$seniority_by_title = as.factor(train_data2$seniority_by_title)
train_data2$Degree = as.factor(train_data2$Degree)
train_data2$Headquarters.Country = as.factor(train_data2$Headquarters.Country)

test_data2 = test_data
test_data2$Type.of.ownership = as.factor(test_data2$Type.of.ownership)
test_data2$Sector = as.factor(test_data2$Sector)
test_data2$Competitors = as.factor(test_data2$Competitors)
test_data2$Job.Title = as.factor(test_data2$Job.Title)
test_data2$seniority_by_title = as.factor(test_data2$seniority_by_title)
test_data2$Degree = as.factor(test_data2$Degree)
test_data2$Headquarters.Country = as.factor(test_data2$Headquarters.Country)
```


```{r}
library(np)
set.seed(1)
fit.kernel_loc <- np::npregbw(formula=Avg.Salary.K. ~ Rating+factor(Size)+Founded+factor(Type.of.ownership)+factor(Sector)
                          + factor(Revenue)+ factor(Competitors) + factor(Python) + factor(spark)+ factor(aws)
                          + factor(excel)+ factor(sql) + factor(sas) + factor(keras) + factor(pytorch)
                          + factor(scikit) + factor(tensor) + factor(hadoop)+ factor(tableau) + factor(bi)
                          + factor(flink)+ factor(mongo) + factor(google_an) + factor(Job.Title)
                          + factor(seniority_by_title)+ factor(Degree)+ factor(Headquarters.Country), 
                          data=train_data2, regtype="lc")
fit.kernel2_loc = npreg(fit.kernel_loc)
summary(fit.kernel2_loc)
par(mfrow = c(2,3))
plot(fit.kernel2_loc, plot.errors.method="bootstrap", plot.par.mfrow=FALSE, random.seed=1)

SSE_kernel = (predict(fit.kernel2_loc, newdata=test_data2)-test_y)^2
MSE_kernel = mean(SSE_kernel); MSE_kernel
SE_MSE_kernel = sd(SSE_kernel)/sqrt(length(test_y));SE_MSE_kernel
```


# Quantile Regression

```{r}
check_ft <- function(x, tau) {
  z <- ifelse(x<0, (tau-1)*x, tau*x)
  return(z)
}
```


```{r}
set.seed(1)
fit_rq <- rq(Avg.Salary.K. ~ ., tau = 0.25, data = train_data)
```

```{r}
fit_rq_pred <- predict(fit_rq, newdata = select(test_data, -Avg.Salary.K.))

SSE_fit_rq <- (check_ft(test_y, tau = 0.25) - check_ft(fit_rq_pred, tau = 0.25))^2
(MSE_fit_rq <- mean(SSE_fit_rq))
(SE_MSE_fit_rq <- sd(SSE_fit_rq)/sqrt(length(test_y)))
```






# Quantile Regression with Lasso Penalty

```{r}
set.seed(1)
cv_rq_pen <- rq.pen.cv(x = train_X, y = train_y, tau = 0.25, penalty = "LASSO")

cv_rq_lambda <- cv_rq_pen$btr$lambda1se
fit_rq_lasso <- rq.pen(x = train_X, y = train_y, tau = 0.25, lambda = c(cv_rq_lambda), 
                       penalty = "LASSO", alg = "br")

coef(fit_rq_lasso) %>% round(3)

newx <- model.matrix(Avg.Salary.K. ~., data = test_data)[, -1]
fit_rq_lasso_pred <- predict(fit_rq_lasso, newx)

SSE_fit_rq_lasso <- (check_ft(test_y, tau = 0.25) - check_ft(fit_rq_lasso_pred, tau = 0.25))^2
(MSE_fit_rq_lasso <- mean(SSE_fit_rq_lasso))
(SE_MSE_fit_rq_lasso <- sd(SSE_fit_rq_lasso)/sqrt(length(test_y)))
```



# XG boost

```{r}
set.seed(1)
xgb_train <- xgb.DMatrix(data = train_X, label = train_y)
xgb_test <- xgb.DMatrix(data = test_X, label = test_y)

watchlist <- list(train=xgb_train, test=xgb_test)
train_xgb <- xgb.train(data = xgb_train, watchlist=watchlist, nrounds = 1000, verbose = 0)
nrounds_xgb <- train_xgb$evaluation_log$test_rmse %>% which.min
fit_xgb <- xgboost(data = xgb_train, max.depth = 3, nrounds = nrounds_xgb, verbose = 0)

summary(fit_xgb)

fit_xgb_pred <- predict(fit_xgb, xgb_test)

SSE_xgb <- (fit_xgb_pred - test_y)^2
(MSE_xgb <- mean(SSE_xgb))
(SE_MSE_xgb <- sd(SSE_xgb)/sqrt(length(test_y)))
```


```{r}
# a plot with all the trees
xgb.plot.tree(model = fit_xgb)

# this seems to be a mess. Hence, we only stick to 1 tree at a time. The below code is to plot first tree and show its node ID
xgb.plot.tree(model = fit_xgb, trees = 3, show_node_id = TRUE)
```




```{r}
coef_nm <- rownames(coef_ridge)

coef_rq <- coef(fit_rq)
coef_rq_lasso <- coef(fit_rq_lasso)
coef_lars <- coefficients.lars[58, ]

data1 <- as.data.frame(summary(coef_ridge)) %>% select(i, Ridge = x)
data2 <- as.data.frame(summary(coef_lasso)) %>% select(i, Lasso = x)
data3 <- data.frame(QR = coef_rq) %>% rownames_to_column() 
data4 <- data.frame(i = 1:length(coef_rq_lasso), coef_rq_lasso) %>%
  `colnames<-`(value = c("i", "QRP")) %>%
  rownames_to_column() %>%
  mutate(rowname = ifelse(rowname == "intercept", "(Intercept)", rowname))
data5 <- data.frame(LARS = coef_lars) %>% rownames_to_column

full_join(data1, data2, by = "i") %>% 
  full_join(data4, by = "i") %>%
  full_join(data3, by = "rowname") %>%
  full_join(data5, by = "rowname") %>%
  select(Variable = rowname, Ridge, Lasso, QR, QRP, LARS) %>%
  mutate(Lasso = replace_na(Lasso, replace = 0), 
         LARS = replace_na(LARS, replace = 0)) %>% 
  pander()

```


